### ISSUE TITLE
[BUG] Documentation Publish is broken

### ISSUE THREAD

**Issue by rexut** [tiacsys/bridle#62]
**Describe the bug**
Since bump to `actions/github-script@v6` in **Documentation Publish** we can't publish the documentation anymore.

**To Reproduce**
see: https://github.com/tiacsys/bridle/actions/runs/3244220989/jobs/5320091332
```
TypeError: Cannot read properties of undefined (reading 'listWorkflowRunArtifacts')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13355:16), <anonymous>:3:38)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13356:12)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13451:26)
    at Module.858 (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13428:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:52:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'listWorkflowRunArtifacts')
```

**Expected behavior**
Build artefact `doc.zip` from **Documentation Build** have to pick up, extract and upload to WEB server.

**Impact**
Can' deliver release or latest documentation. Can't remove old documentation on WEB server.

**Logs and console output**
non

**Screenshots**
non

**Development Environment (please complete the following information):**
 - GitHub action runner (workflow)

**Additional context**
non

**Comment by rexut** [comment]
seems to be similar to actions/github-script#242
